@host = http://192.168.130.142:3000

###

POST {{host}}/arena/create
Content-Type: application/json

{
    "arenaType": "private",
    "countdownToStart": 24,
    "gameLength": 43200,
    "players": [
        { "sharkName": "ryan" }
    ]
}

###

GET {{host}}/public-arenas 

###

GET {{host}}/arena/0000-002V/settings
